#!/bin/bash
set -e

WELCOMING_HOSTS_FILE=~/.ssh/welcoming-hosts
IDENTITY_FILE=~/.ssh/id_ed25519.pub

WELCOMING_HOSTS=$(cat $WELCOMING_HOSTS_FILE)

echo Pick the source of keys that can be used to access all the interesting hosts:
select PRECEDING_AUTHORIZED_USER_HOST in $WELCOMING_HOSTS; do
    echo We are going to borrow the keys from $PRECEDING_AUTHORIZED_USER_HOST \
         to distribute the local $IDENTITY_FILE to all the WELCOMING_HOSTS
    ssh -A $PRECEDING_AUTHORIZED_USER_HOST -t ssh-add
    break
done

for USER_HOST in $WELCOMING_HOSTS; do
    ssh-copy-id -i $IDENTITY_FILE $USER_HOST
done

ssh-add -D
