#!/bin/bash
set -e

pushd $(dirname $0)

mkdir -p ~/bin/
mkdir -p ~/.config/nvim/

ln -sf `realpath bin/sagent` ~/bin/
ln -sf `realpath bin/watche` ~/bin/

echo . `realpath bin/set-env-vars` >> ~/.bash_aliases

ln -sf `realpath .tmux.conf` ~/
ln -sf `realpath .gitconfig` ~/
ln -sf `realpath .gdbinit`   ~/
ln -sf `realpath .config/nvim/init.vim` ~/.config/nvim/

popd
